puts "Testing out \\ Escape Sequences"
puts " \' \" "
puts "Trying out \a to see what happens"
puts "Same with\b \\b "
puts "What will \f formfeed do?"
puts "We all know that \n will put this on a seperate line\n and \t will tab this"
puts "But what is \r Carriage return or a \v vertical tab?"
puts "Lets try \011 for a horizontal tab or \x9 for another one"
puts "Finally lets try \u0001 just to see if it works"
